### ISSUE TITLE
FATAL000: No version was supplied

### ISSUE THREAD

**Issue by Mutaz94** [metrumresearchgroup/babylon#154]
Hi all. I guess this is the first issue outside Metrum. What I did is installing release v2.1. I did install bbi from the Metrum tap. `brew bbi install` and get everything together. 
I tried to run a model 
```

% bbi init
 % bbi nonmem run local run11.mod

```

and this is what I got 

![Screen Shot 2020-03-27 at 8 10 20 PM](https://user-images.githubusercontent.com/35429067/77811299-72e87200-7067-11ea-9fe7-d500dd47ce0a.png)

Any thoughts? (P.S. I use Mac OSX Catalina v10.15)

**Comment by Mutaz94** [comment]
I guess its something related to NONMEM path? its not recognizing it?

**Comment by dpastoor** [comment]
Thanks for giving it a whirl! Can you post your babylon.yaml file. It's saying it doesn't know which version to use since you never specified a version in the run command or a default on the config.

**Comment by Mutaz94** [comment]
Sure! 
```
nonmem: "nm75b1"
babylon_binary: /usr/local/bin/bbi
clean_lvl: 1
git: true
local:
  create_child_dirs: true
mpi_exec_path: /usr/local/mpich3/bin/mpiexec
nmfe_options:
  maxlim: 100
output_dir: '{{ .Name }}'
parallel: false
parallel_timeout: 2147483647
save_config: true
threads: 12
```

**Comment by Mutaz94** [comment]
nm75b1 is the file containing NONMEM v 7.5 beta

**Comment by dpastoor** [comment]
ah ok that config isn't fully correct. nonmem is actually a key where you can specify specific nonmem versions by a key name. This would allow you to also install nm74 alongside.

```
nonmem:
  nm75:
    executable: nmfe75
    home: /opt/NONMEM/nm75b1
    default: yes

```

Then when running, it will look for the default version, or if you want to specify an alternative you can use the `--nm_version` flag to specify the key (in this case `nm75`
